// Generated by CoffeeScript 1.4.0
(function() {
  var ComfoAir, comfolink, http, sys;

  sys = require('sys');

  http = require('http');

  ComfoAir = require('rpi-comfoair');

  comfolink = new ComfoAir('/dev/ttyAMA0');

  http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    return res.end('Hello World 2\n');
  }).listen(1337, '192.168.178.44');

  console.log('Server running at http://192.168.178.44:1337/');

  comfolink.on('temp', function(data) {
    return console.log(data);
  });

}).call(this);
